# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-04 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0017_auto_20180407_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('posted',)},
        ),
    ]
